---
title: "Perez_CV"
output: github_document
---

# Logan Perez

loperez@uark.edu  
loganoperez01@gmail.com  

---

# EDUCATION

**University of Arkansas**  \hfill August 2024 – Present  
Advisors: Drs. Michael Douglas & Marlis Douglas  
M.S. Statistics & Analytics ~ Bio-analytics  

**University of Arkansas ~ Fort-Smith (UAFS)**  
B.S. Biology, cum laude  
Overall GPA: 3.74  
August 2020 - May 2024  

Study abroad ~ Belize: Studied mutualism & documented biodiversity  
May 2023  

---

# RESEARCH PROJECTS

❖ **Graduate Researcher** \hfill January 2025 – Present  
University of Arkansas, Fayetteville  

**Project 1: Forecast-Modeling of Cartilaginous Fishes in New Zealand**  
Principal Investigators: Drs. Michael Douglas & Marlis Douglas  

Description: Forecast the total commercial catch of cartilaginous fishes in New Zealand by 2030 using open-access data sourced from the Ministry for Primary Industries, a governmental entity.  

Relevant Skills: R-based data analysis, Linux-based data cleaning, statistical analysis, open-sourced data collection, and predictive model selection.  

**Project 2: Spring water level and year-class strength in Largemouth Bass**  

Principal Investigators: Drs. Michael Douglas & Marlis Douglas | Arkansas Game & Fish  

Description: Determine how changes in spring water levels influence Largemouth Bass spawning and year-class strength in Lake DeGray  

Relevant Skills: R-based data analysis, statistical analysis, working with long-term ecological datasets, and collaboration with public entities.  

---

❖ **REU Research Fellow** \hfill May 2023 – August 2023  
Miami University, Oxford, Ohio  

Project: Estimating litter size and evaluating body condition in White-tailed deer  

Principal Investigator: Dr. David Gorchov  

Description: Estimated body condition of two White-tailed deer populations using shrub cover analysis, I3s software to link does to fawns, and ImageJ to distinguish doe age groups.  

Relevant Skills: Trail camera data collection, wildlife monitoring, I3s software, ImageJ, and experimental protocol design.  

---

❖ **Undergraduate Researcher** \hfill August 2021 – May 2023  
University of Arkansas, Fort-Smith  

**Project 1: Biochar as a bioremediation application**  

Principal Investigator: James Brandli  

Description: Inoculated charcoal in fish emulsion to examine the effects on Turf grass production  

Relevant Skills: Greenhouse maintenance, biohazard training, scientific communication  

**Project 2: The effects of green tank on food fish in an aquaculture environment**  

Principal Investigator: James Brandli  

Description: Evaluated the growth and behavioral response of year of young Tilapia in a variety of green aquacultural tanks.  

Relevant Skills: Animal maintenance & care, aquaculture development, fish sex determination  

---

# SCHOLARSHIPS & GRANTS

❖ University of Arkansas GSIE Presentation Travel Grant 2025  
Amount: $700  

❖ Arkansas Academic Challenge Scholarship 2020  
Amount: $14,000  

❖ UAFS Academic Excellence Scholarship 2020  
Amount: $12,000  

❖ Faye Ferguson Thomas Scholarship 2020  
Amount: $8,000  

❖ Arkansas Scholars Scholarship 2020  
Amount: $2,000  

❖ M.H. Bill Simmons Memorial Scholarship 2020  
Amount: $2,000  

---

# HONORS & AWARDS

❖ UAFS Chrysalis Award 2022  

❖ UAFS Research Symposium Winner 2022  

---

# ORAL PRESENTATIONS

❖ Perez, L., Elea, C., Gorchov, D. 2023. Evaluating Body Conditions of White-tail deer Based on The Average Litter Size of a Population. Miami University Annual REU Research Forum. August 2023, Oxford, Ohio.  

---

# POSTER PRESENTATIONS

❖ Perez, L., Richardson, R., Douglas, MR., Douglas, ME. 2025. A Predictive Approach: ETS Modeling of Cartilaginous Fishes. Annual AFS Conference meeting. August 2025, San Antonio, Texas  

❖ Perez, L., Richardson, R., Douglas, MR., Douglas, ME. 2025. StAn/BioAnalytics: The fundamentals of Conservation. Arkansas Annual AFS Conference meeting. February 2025, Little Rock, Arkansas  

❖ Perez, L., Gambill, P., Elam, B., and James, J. 2022. The Effects of Biochar on Turf Grass. The University of Arkansas Fort-Smith Annual Symposium. April 2022, Fort-Smith, Arkansas  

---

# TEACHING

❖ **Teaching Assistant**  
Department of Biology, University of Arkansas, Fayetteville \hfill August 2024 – Present  

Teaching Assistant for Principles of Biology ~ Lab Instructor  

○ Prepare laboratory experiments and materials to support weekly lessons  

○ Teach and guide students through hands-on biological experiments  

○ Assess student performance and provide feedback  

---

# PROFESSIONAL EXPERIENCE

❖ **Lab Assistant** \hfill May 2025 – August 2025  
University of Arkansas, Fayetteville  

○ Prepared and maintained lab materials, assisted in exam development, contributed to semester supply planning, managed safety and first aid resources, and supported undergraduate teaching through green roof maintenance.  

❖ **Lab Assistant** \hfill August 2022 – May 2024  
University of Arkansas, Fort-Smith  

○ Prepared and organized chemicals, specimens, equipment, and instructional resources for General Biology and Zoology labs.  

---

# TECHNICAL SKILLS AND TRAINING

● Proficient R statistical analysis and figure production skills  

● Basic Proficient Python Programming  

● Linux command-line proficiency  

● SPSS Statistical Analysis  

● I3s pattern recognition software  

● DNA extraction (QIAamp Fast DNA Kit)  

● Applied transect sampling techniques  

● Trail-camera sampling techniques  

● Media preparation: nutrient agar/water agar


